name: Java CI with Maven

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean compile --file pom.xml

    - name: Run tests
      run: mvn -B test --file pom.xml

    - name: Generate test report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Maven Tests
        path: '**/surefire-reports/*.xml'
        reporter: java-junit
        fail-on-error: false